function g = gb(ax,ay,az,bax,bay,baz,bphi,btheta,dt,phi,psi,sax,say,saz,swx,swy,swz,theta,wx,wy,wz,x,xd,y,yd,z,zd)
%GB
%    G = GB(AX,AY,AZ,BAX,BAY,BAZ,BPHI,BTHETA,DT,PHI,PSI,SAX,SAY,SAZ,SWX,SWY,SWZ,THETA,WX,WY,WZ,X,XD,Y,YD,Z,ZD)

%    This function was generated by the Symbolic Math Toolbox version 5.6.
%    28-Apr-2013 22:15:14

t608 = dt.^2;
t609 = cos(theta);
t610 = sin(psi);
t611 = cos(psi);
t612 = sin(phi);
t613 = sin(theta);
t614 = -az+baz+saz;
t615 = cos(phi);
t616 = -ax+bax+sax;
t617 = -ay+bay+say;
t618 = t609.*t611;
t644 = t610.*t612.*t613;
t619 = t618-t644;
t620 = t609.*t610;
t621 = t611.*t612.*t613;
t622 = t620+t621;
t623 = t612.*t614;
t624 = t611.*t615.*t617;
t625 = t623+t624-t610.*t615.*t616;
t626 = t611.*t613;
t627 = t609.*t610.*t612;
t628 = t626+t627;
t629 = t616.*t628;
t630 = t610.*t613;
t641 = t609.*t611.*t612;
t631 = t630-t641;
t632 = t617.*t631;
t633 = t609.*t614.*t615;
t634 = t629+t632+t633+9.81e2./1.0e2;
t635 = swx+wx;
t636 = dt.*t635;
t637 = cos(t636);
t638 = swy+wy;
t639 = dt.*t638;
t640 = sin(t636);
t642 = sin(t639);
t643 = cos(t639);
t645 = swz+wz;
t646 = dt.*t645;
t647 = sin(t646);
t648 = cos(t646);
g = [x+dt.*xd-t608.*t616.*t619.*(1.0./2.0)-t608.*t617.*t622.*(1.0./2.0)+t608.*t613.*t614.*t615.*(1.0./2.0);y+dt.*yd-t608.*t625.*(1.0./2.0);z+dt.*zd-t608.*t634.*(1.0./2.0);xd-dt.*(t616.*t619+t617.*t622-t613.*t614.*t615);yd-dt.*t625;zd-dt.*t634;asin(t611.*t615.*t640+t612.*t637.*t643+t610.*t615.*t637.*t642);atan2((-t622.*t640+t619.*t637.*t642+t613.*t615.*t637.*t643),(t631.*t640-t628.*t637.*t642+t609.*t615.*t637.*t643));atan2((-t612.*(t642.*t648+t640.*t643.*t647)+t610.*t615.*(t643.*t648-t640.*t642.*t647)+t611.*t615.*t637.*t647),(t612.*(t642.*t647-t640.*t643.*t648)-t610.*t615.*(t643.*t647+t640.*t642.*t648)+t611.*t615.*t637.*t648));bax+dt.*sax;bay+dt.*say;baz+dt.*saz;bphi;btheta];
