function h = h(phi,psi,theta,x,y,z)
%H
%    H = H(PHI,PSI,THETA,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 5.6.
%    28-Apr-2013 21:55:33

h = [x;y;z;phi;theta;psi];
