function g = g_JB(dt,phi,psi,svx,svy,svz,swx,swy,swz,theta,vx,vy,vz,wx,wy,wz,x,y,z)
%G_JB
%    G = G_JB(DT,PHI,PSI,SVX,SVY,SVZ,SWX,SWY,SWZ,THETA,VX,VY,VZ,WX,WY,WZ,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    30-Apr-2013 12:56:55

t2 = cos(theta);
t3 = sin(psi);
t4 = cos(psi);
t5 = sin(phi);
t6 = sin(theta);
t7 = svz+vz;
t8 = cos(phi);
t9 = svy+vy;
t10 = svx+vx;
t11 = t3.*t6;
t27 = t2.*t4.*t5;
t12 = t11-t27;
t13 = t4.*t6;
t14 = t2.*t3.*t5;
t15 = t13+t14;
t16 = swz+wz;
t17 = dt.*t16;
t18 = swx+wx;
t19 = dt.*t18;
t20 = sin(t19);
t21 = swy+wy;
t22 = dt.*t21;
t23 = sin(t22);
t24 = sin(t17);
t25 = cos(t22);
t26 = cos(t17);
t28 = cos(t19);
t29 = t24.*t25;
t30 = t20.*t23.*t26;
t31 = t29+t30;
t32 = t23.*t24;
t33 = t32-t20.*t25.*t26;
t34 = t15.*t31+t2.*t8.*t33+t12.*t26.*t28;
t35 = t12.*t20;
t36 = t2.*t8.*t25.*t28;
t37 = t35+t36-t15.*t23.*t28;
t38 = t2.*t4;
t39 = t38-t3.*t5.*t6;
t40 = t25.*t26;
t45 = t20.*t23.*t24;
t41 = t40-t45;
t42 = t23.*t26;
t43 = t20.*t24.*t25;
t44 = t42+t43;
t46 = t2.*t3;
t47 = t4.*t5.*t6;
t48 = t46+t47;
g = [x+dt.*(t10.*t39+t9.*t48-t6.*t7.*t8);y+dt.*(t5.*t7-t3.*t8.*t10+t4.*t8.*t9);z+dt.*(t9.*t12+t10.*t15+t2.*t7.*t8);angle(t35+t36+t15.*t31.*1i+t2.*t8.*t33.*1i+t12.*t26.*t28.*1i-t15.*t23.*t28);angle(t15.*t41.*-1i+sqrt(t34.^2+t37.^2)-t2.*t8.*t44.*1i+t12.*t24.*t28.*1i);angle(t5.*t44.*1i+t39.*t41-t3.*t8.*t41.*1i-t6.*t8.*t44-t24.*t28.*t48-t4.*t8.*t24.*t28.*1i)];
