function h = h_JB(phi,psi,theta,x,y,z)
%H_JB
%    H = H_JB(PHI,PSI,THETA,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    30-Apr-2013 12:57:26

h = [x;y;z;phi;theta;psi];
