function h = hc(bphi,btheta,phi,psi,theta,x,y,z)
%HC
%    H = HC(BPHI,BTHETA,PHI,PSI,THETA,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    30-Apr-2013 12:15:43

h = [x;y;z;bphi+phi;btheta+theta;psi];
