function g = g(dt,phi,psi,svx,svy,svz,swx,swy,swz,theta,vx,vy,vz,wx,wy,wz,x,y,z)
%G
%    G = G(DT,PHI,PSI,SVX,SVY,SVZ,SWX,SWY,SWZ,THETA,VX,VY,VZ,WX,WY,WZ,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 5.6.
%    28-Apr-2013 21:55:29

t406 = cos(theta);
t407 = sin(psi);
t408 = cos(psi);
t409 = sin(phi);
t410 = sin(theta);
t411 = svz+vz;
t412 = cos(phi);
t413 = svy+vy;
t414 = svx+vx;
t415 = swx+wx;
t416 = dt.*t415;
t417 = cos(t416);
t418 = swy+wy;
t419 = dt.*t418;
t420 = sin(t416);
t421 = t407.*t410;
t422 = t421-t406.*t408.*t409;
t423 = sin(t419);
t424 = t408.*t410;
t425 = t406.*t407.*t409;
t426 = t424+t425;
t427 = cos(t419);
t428 = t406.*t407;
t429 = t408.*t409.*t410;
t430 = t428+t429;
t431 = t406.*t408;
t432 = t431-t407.*t409.*t410;
t433 = swz+wz;
t434 = dt.*t433;
t435 = sin(t434);
t436 = cos(t434);
g = [x+dt.*(t413.*t430+t414.*t432-t410.*t411.*t412);y+dt.*(t409.*t411-t407.*t412.*t414+t408.*t412.*t413);z+dt.*(t413.*t422+t414.*t426+t406.*t411.*t412);asin(t408.*t412.*t420+t409.*t417.*t427+t407.*t412.*t417.*t423);atan2((-t420.*t430+t417.*t423.*t432+t410.*t412.*t417.*t427),(t420.*t422-t417.*t423.*t426+t406.*t412.*t417.*t427));atan2((-t409.*(t423.*t436+t420.*t427.*t435)+t407.*t412.*(t427.*t436-t420.*t423.*t435)+t408.*t412.*t417.*t435),(t409.*(t423.*t435-t420.*t427.*t436)-t407.*t412.*(t427.*t435+t420.*t423.*t436)+t408.*t412.*t417.*t436))];
