all:
	cd src; make
	cd drivers/Joystick; make
	cd drivers/ViconNew; make
	cd ipc; make
	cd api; make
	cd matlab/utils; make
	cd interfaces/kQuadIface-12.12.12; make

clean:
	cd src; make clean
	cd drivers/Joystick; make clean
	cd drivers/ViconNew; make clean
	cd ipc; make clean
	cd api; make clean
	cd matlab/utils; make clean
	cd interfaces/kQuadIface-12.12.12; make clean

